import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync} from "fs";
import { resolve } from "path"
import {execSync } from "child_process"

const apiVersions = [
  "2024-11-01-preview",
  "2025-07-01-preview"
]
const runMain = () => {
  console.log("***********************************")
  const dirs = []
  const makeDirs  = () => {
    for( const apiVersion of apiVersions ) {
      const _dirs = [
        {
          inDir: `specification/sciencedev/data-plane/Microsoft.Science.Catalog/preview/${apiVersion}/examples`,
          outDir:
            `specification/sciencedev/Science.Catalog/examples/${apiVersion}`,
        },

        {
          inDir:
            `specification/sciencedev/data-plane/Microsoft.Science.Workspace/preview/${apiVersion}/examples`,
          outDir:
            `specification/sciencedev/Science.Workspace/examples/${apiVersion}`,
        },

        {
          inDir:
            `specification/sciencedev/resource-manager/Private.Science/preview/${apiVersion}/examples`,
          outDir:
            `specification/sciencedev/Science.Management/examples/${apiVersion}`,
        },
      ];
      for(const _dir of _dirs) {
        dirs.push(_dir)
      }
    }
    return dirs;

  }
  for(const { inDir, outDir } of makeDirs()) {
    const outDirPath = resolve(outDir)

    console.log("\nDeleting:", outDirPath)
    rmSync(outDirPath, { recursive: true, force : true })
    mkdirSync(outDirPath)
    console.log("\n------------------------")
    console.log("Processing: ", inDir)
    for(const file of readdirSync(inDir)) {
      const filePath = resolve(inDir, file);
      console.log("   - ", file)
      let {title, ...contents} = JSON.parse(readFileSync(filePath, "utf8"));
      if(title.indexOf("] rule") > 0) {
        title = title.substring(0,title.indexOf("] rule")+ ("] rule".length))
      }
      if(file.includes("_MaximumSet")) {
        title = title.replaceAll("MinimumSet", "MaximumSet");
        if(!title.endsWith(" - generated by [MaximumSet] rule")) {
          title = `${title} - generated by [MaximumSet] rule`
        }

      } else if(file.includes("_MinimumSet")) {
        title = title.replaceAll("MaximumSet", "MinimumSet");
        if(!title.endsWith(" - generated by [MinimumSet] rule")) {
          title = `${title} - generated by [MinimumSet] rule`
        }
      }
      writeFileSync(
        filePath,
          JSON.stringify({
          title,
          ...contents,
        }, null, 2)
      )
      writeFileSync(
        resolve(outDirPath, file),
        JSON.stringify({
          title,
          ...contents,
        }, null, 2)
      )
    }
  }
  execSync("npx prettier -w specification/sciencedev/**/*.json", {stdio: 'pipe'})
  const packageDirs = [
    "./specification/sciencedev/Science.Management",
    "./specification/sciencedev/Science.Workspace",
    "./specification/sciencedev/Science.Catalog",
  ]
  for(const pkg of packageDirs) {
    const pkgPath = resolve(pkg)
    try {
      execSync(`npx tsv ${pkgPath}`, { stdio: 'inherit' })
    } catch (err) {
      console.warn(err)
    }
  }
}
runMain()
