// -----------------------------------------------------------------------
// <copyright file="sharedResources.tsp" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

import "./common/base.tsp";
import "./models/AccessPointAccount.tsp";
import "./models/UpdateGroup.tsp";
import "./models/Network.tsp";
import "./models/Device.tsp";
