// -----------------------------------------------------------------------
// <copyright file="main.tsp" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

// Import the shared main file for all common Azure Access service types
import "../Access.Management.Shared/sharedResources.tsp";

// Import servie related to non-PrivateRP Azure Access Service
import "./modules/services/accessPointService.tsp";
