// -----------------------------------------------------------------------
// <copyright file="main.tsp" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

import "../Access.Management.Shared/modules/common/base.tsp";
import "../Access.Management.Shared/modules/resources/accessPointResource.tsp"; // To be updated later as child of site
import "../Access.Management.Shared/modules/resources/circuit.tsp";
import "../Access.Management.Shared/modules/resources/device.tsp";
