// -----------------------------------------------------------------------
// <copyright file="main.tsp" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

import "../EncryptedTransport.Management.Shared/modules/common/base.tsp";
import "../EncryptedTransport.Management.Shared/modules/resources/encryptedTransportAccount.tsp";
